### PR TITLE
Added requirements to prevent system level deadlock

### PR DESCRIPTION
**Pull request by Silabs-ArjanB**
Signed-off-by: Arjan Bink <Arjan.Bink@silabs.com>

### CODE REVIEW

**Review by davideschiavone — COMMENTED** [review]
@moimfeld can you check if this applies to your case pls?

**Comment by Silabs-ArjanB** [comment]
Addresses https://github.com/openhwgroup/core-v-xif/issues/39

**Comment by moimfeld** [comment]
Hi @Silabs-ArjanB and @davideschiavone 

I checked the implementation of the cv-x-if on cv32e40p and the FPU subsystem, and this rule already applies to both. But I find it a good idea to add it to the specs.

**Comment by Silabs-ArjanB** [comment]
@moimfeld Did you run into deadlock issues before?

**Comment by moimfeld** [comment]
@Silabs-ArjanB Not really, while designing the FPU subsystem (and implementing the cv-x-if on cv32e40p) I had some issues with "infinite stalls" and some combinational loops. But the "infinite stalls" occurred because I did not clear some status signal properly and the combinational loops occurred because of some FPU subsystem-internal handshakes. So when I had issues, they were not caused by the interface. 

But keep in mind, that I have not done any coverage driven constraint random verification.

**Pull request merged**
